### ISSUE TITLE
README for target platform installation

### ISSUE THREAD

**Issue by trutzonline** [qos-ch/logback-beagle#1]
Create a README for developers, who want to play around with code, containing:
- target platform preparation step-by-step
- description of main components like BeagleTable and BeagleSocketServer

**Comment by ceki** [comment]
There is a jira project for logback-beagle. See http://jira.qos.ch/browse/CONSPLUG

**Comment by trutzonline** [comment]
Jira issue created: http://jira.qos.ch/browse/CONSPLUG-27
